client/js/components/editor-codeblock.js, client/js/components/editor.js
Please enter the commit message for your changes. Lines starting
In the original code, the vueCodeblock doesn't work properly.
More specifically, it functions correctly at the first click. However, after click the "insert code block" or "discard", there is no possibility to call the vueCodeblock windows again expect for refreshing the whole page.
The problem is that mdeModalOpenState  is set to be true in editor.js. The value seems not to be changed in function cancel() in editor-codeblock.js (Sorry I am novice in js but I am guessing that the value instead of the reference is passed.)
My minor update actually copy the same idea from editor-image.js, moving the assignment of the mdeModalOpenState inside.
While, I am guessing that there are still two copy of mdeModalOpenState in these two …
=> fixed code block bugs

server/index.js
- replace `process.kill()` which is causing infinite loop of `graceful` callback
- terminate background agent to fix `warn: [AGENT] Lost connection to main server. Exiting...` error
=> Fix graceful termination issues

.gitignore, config.sample.yml, server/app/data.yml, server/libs/config.js, server/views/pages/view.pug
```yml
theme:
...
viewSource: "all"            # "all" | "write" | "none"
```
- `All` will always show the view source button.
- `Write` will show the view source button for those with the ability to edit the page (write access)
- `none` will never show the view source button.
Additional notes:
- added sublime project to gitignore
- closes enhancement issue: #221 
- The docs should be updated to show this option.
=> Add viewSource theme config to toggle view source Button

server/models/user.js
LDAP queries to Open Directory on macOS Server don't include a "displayName" attribute, but the first name + surname combo is available in the "cn" attribute.
=> also check "cn" attribute for display name

server/locales/ja/browser.json
It prefers to use "検索" to "検査" for "search".
=> Revise ja text.

server/agent.js
Fixes #297.
I filtered out not only `.git/index`, but the whole `.git` directory - I suppose you didn't intend to scan those for cache.
=> do not descend into .git directory when updating cache from agent

config.sample.yml
The variable name must be enclosed in parentheses, otherwise it
is interpreted verbatim.
Move this tip to the top of the file, since it applies to all fields,
not just the 'db' field.
=> config.sample.yml: fix syntax for using ENV variables

server/libs/rights.js
Strips the edit and create url segments from the start of the path, which fixes the issue that requires you to add extra permission sets for `/create/...` and `/edit/...`
Fixes #147
=> Strip out edit and create from start of path in rights

server/libs/git.js
i18next escapes paths by default, which shouldn't be necessary in this case.
=> fix #185: avoid escaping paths in commit messages

.gitignore, config.sample.yml, package.json, server/controllers/auth.js, server/libs/auth.js, server/locales/en/auth.json, server/views/auth/login.pug, yarn.lock
Hello there,
I recently installed wikijs and needed to make it work with Keycloak, however I stumbled upon the issue #436. I didn't want to mess with the oauth2 authentication, so I implemented the OpenID Connect version.
The configuration file has been updated with the following : 
```yml
oidc:
enabled: false
clientId: OPENID_CONNECT_CLIENT_ID
clientSecret: OPENID_CONNECT_CLIENT_SECRET
issuer: OPENID_CONNECT_ISSUER
userInfoUrl: OPENID_CONNECT_USER_INFO_URL
authorizationURL: OPENID_CONNECT_AUTHORIZATION_URL
tokenURL: OPENID_CONNECT_TOKEN_URL
emailClaim: OPENID_CONNECT_EMAIL_CLAIM_PATH
usernameClaim: OPENID_CONNECT_USERNAME_CLAIM_PATH
```
The following parameters are the same as the OAuth2 : 
- clientId
- clientSecret
- authorizationURL
- tokenURL
The following parameters are specific to …
=> Added OpenID Connect support

server/app/data.yml, server/index.js
Hi there!
I had a need to restrict access to localhost, and couldn't find a way to do that in the documentation. This change allows setting listen_address in config.yml, the setting defaults to 0.0.0.0 (which binds all addresses, AFAIK).
=> Added listen_address configuration option

tools/docker-compose.yml
Because v4 is out and WikiJS doesn't seem to work with it
=> Lock MongoDB to v3

README.md
The link to the CONTRIBUTING.md file was broken. It didn't have /.github/ in the path.
Old link: https://github.com/Requarks/wiki/blob/master/CONTRIBUTING.md
New link: https://github.com/Requarks/wiki/blob/master/.github/CONTRIBUTING.md
=> Fix Contribute link

README.md
Link to Change Log in README.md is not working (404) because it is pointing to a no-longer existing branch `dev`.
=> Fix link to Changelog

dev/build/Dockerfile
Best practices for docker images is to run containers as non-root user. For example using Kubernetes with the [restricted pod security policy](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/privileged-psp.yaml), it is not possible to start the current image.
Therefore, the user is changed to `node` which is the recommended user for node images (see https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user).
After building the docker image and running the example setup with docker-compose, I got the following log messages. I run the setup and created an example page:
```
wiki_1_f0de2a07b8a9 | 2019-03-29T22:12:13.176Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
wiki_1_f0de2a07b8a9 | …
```
=> Run docker image as non-root

server/db/migrations-sqlite/2.0.0-beta.127.js
without this code:  `.defaultTo('')`
I got error:   Database Initialization Error: alter table `assets` add column `hash` varchar(255) not null - SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
=> set default value to ''

server/core/localization.js
Locale override options were not working for me with the latest code due to fs.readFileAsync no longer existing in the latest node version. Error was silence too, so there was no feedback to the developer about the issue occurring. This patch should fix it though
=> fix: locale override not loading

client/components/setup.vue, dev/webpack/webpack.dev.js
vee validate scopes are used but they are missing in errors parameter
=> fix: error messages are not shown in setup

client/components/editor/editor-modal-media.vue, client/store/editor.js
Before this, it was a hassle to insert multiple media assets nested deeply in folders, because on every reopen of the editor media modal, the path was reset.
1. Open media editor
2. Click through folder structure `a/b/c/d`
3. Insert image
4. Open media editor again - *path is reset*
5. Click through folder structure `a/b/c/d` *again*
6. Insert image
7. Rinse and repeat
Now, the modal saves the path, so:
1. Open media editor
2. Click through folder structure `a/b/c/d`
3. Insert image
4. Open media editor again ~~- *path is reset*~~
5. ~~Click through folder structure `a/b/c/d` *again*~~
6. Insert image
7. Rinse and repeat
It makes a huge difference when working with many assets and organizing them into folders nested more than one level deep.
---
Technically it simply moves the current …
=> save editor media asset path on reopen

dev/openshift/Dockerfile
This Dockerfile extends the `wiki:beta` image to update permissions on the application directories so the `root` group has identical permissions to the `node` user.  
Additional details can be found in OpenShift's documentation: https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines
This was tested on OpenShift v3.11.
=> OpenShift-compatible Dockerfile

server/modules/rendering/html-core/renderer.js
Fixing typo on: "server\modules\rendering\html-core\renderer.js"
Lines 40 and 41. Invalid reference to "WIKI.config.site.host" -- should be: "WIKI.config.host"
This was causing rendering issues when attempting to create some sample pages; such as: https://github.com/jbaez001/markdown-cheatsheet
Submitted #1020 for this. Possibly related to #847 as well.
=> Fixing typo on html-core renderer

package.json, server/modules/rendering/markdown-plantuml/definition.yml, server/modules/rendering/markdown-plantuml/renderer.js, yarn.lock
uses [markdown-it-plantuml](https://www.npmjs.com/package/markdown-it-plantuml).
Doesn't work in preview pane yet. Does the preview pane use a different rendering pipeline?
=> Plantuml markdown

server/modules/analytics/baidutongji/code.yml, server/modules/analytics/baidutongji/definition.yml
Baidu Tongji is an alternative product to Google Analytics. It's the one largest website tracking and analytics service in China market.
--
=> Support Baidu Tongji analytics module

package.json, yarn.lock
Fixing problem with dragging navigation in navigation admin section (cannot drag and drop) by bumping version of `vuedraggable` to 2.23.2 as discussed in this issue.
https://github.com/SortableJS/Vue.Draggable/issues/730
=> Fix: drag and drop for navigation admin

client/components/admin/admin-groups-edit-rules.vue
Fix #997 .
Simply change the `removeRule` implementation on the client side should do the trick.
=> Fix remove page rules always remove the bottom rule

client/components/admin/admin-groups-edit.vue
The trash icon button in `admin-groups-edit.vue` is not working (dialog not opened when clicked). Fix syntax according to [vuetify docs](https://vuetifyjs.com/en/components/dialogs) and dialog is opened again. 
Trash button
Vuetify docs
=> Fix opening delete group dialog

client/components/admin/admin-groups-edit.vue
After the Delete Group Modal opened I get this message
```
[Vuetify] [BREAKING] 'flat' has been removed, use 'text' instead. For more information, see the upgrade guide https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide
```
This PR will fix this.
=> Fix v-btn flat is deprecated

dev/examples/docker-compose.yml
This network is unnecessary because Compose creates a network for all services by default.
=> remove `wikinet` network from docker-compose.yml example

config.sample.yml, server/app/data.yml, server/controllers/upload.js, server/core/config.js, server/core/sideloader.js, server/core/system.js, server/jobs/purge-uploads.js, server/models/assets.js, server/models/pages.js, server/modules/storage/git/storage.js, server/setup.js
According to the [defaults](https://github.com/Requarks/wiki/blob/master/server/app/data.yml#L60) one can set the data and content paths in the config file. However that wasn't used anywhere until now (besides once in `purge-uploads.js`).
I think the content path isn't used anywhere? Should I remove that one?
=> Actually use path variables as given in default config

server/jobs/rebuild-tree.js
**Fixes issue when tree is being rebuilt with mssql backend.**
I added a condition to only execute the wrapping with the IDENTITY_INSERT on an mssql type database. I already tested this fix in my docker container by modifying the files according to this pull request. The `rebuild index` is working as I expected it to work.
At the moment I do not have the time to verify other database backends, but if this is mandatory for merging this PR please let me known and I will try to validate during the next days.
Is there anything else I can do to help getting this PR into the main repo?
=> Adds IDENTITY_INSERT in rebuild-tree.js #1125

server/models/analytics.js, server/models/pages.js
Fixes #1036
Fixes #1035
Replace pages.* in select query with explicit list of columns to avoid multiple identically named columns being returned by MSSQL triggering a graphQL error.
=> Expand pages.* to prevent duplicate columns in MSSQL

server/modules/search/postgres/definition.yml
Previously: "Dictionnary"
Now: "Dictionary"
=> Fixed Typo in PostgreSQL

client/themes/default/components/page.vue
Fixes #1221.
The issue boils down to a peculiar difference in flex behavior in Safari vs Chrome/Firefox. I distilled the code down to this snippet:
```html
<!DOCTYPE html>
<html>
<head>
<style>
.outer {
height: 90px;
display: flex;
flex-wrap: wrap;
align-content: center;
background: red;
}
.inner {
/* When vertical margins are not set to auto, .inner grows to the fill .outer in Safari,
whereas in Chrome/Firefox .inner shrinkwraps its contents. */
/* margin: auto 0; */
flex-grow: 1;
background: yellow;
}
</style>
</head>
<body>
<div class="outer">
<div class="inner">
<div>Line 1.</div>
<div>Line 2.</div>
</div>
</div>
</body>
</html>
```
Test page: https://gitcdn.xyz/cdn/zmwangx/fa93c33e1e8cb9e83cd494bc39e3c9a1/raw/97c1e6d23473514811a3703e034b24a13d81f19e/flex.html
In Chrome/Firefox, the …
=> Fix wrong page title positioning in Safari

client/components/admin/admin-system.vue
Select Node.js and PostgreSQL version strings are now selectable
Fix #1246
=> Select Node.js and PostgreSQL version strings

client/components/editor/editor-markdown.vue
Apply fb0c64a07e9fceb457dd1c6f19896bcc73d7d77b to MD editor preview.
=> exclude non-class attributes from markdown rendering in editor preview

client/themes/default/scss/app.scss
This removes the fancy tick-mark next to unordered list items, which is
a little depressing, but fixes formatting for them when they contain
paragraphs (`<p>` elements). The tick-mark has been replaced with
a square mark. Both ordered and unordered lists have grown 1rem of left
padding to compensate for their position.
Considered using disclosure-closed as a similar triangle replacement,
but it's not regarded as something that should be used in production
(per MDN). Using a simple string is unsupported because it's only in
a CSS working draft, so a square is the least controversial option,
I think.
Closes #1282.
=> Fix list item formatting for lists with paragraphs

server/helpers/page.js
This excludes the trailing slash from the locale code.
=> fix: getPagePath returns trailing slash on locale (#1323)

server/jobs/rebuild-tree.js
MSSQL has a limit of 2100 parameters per query. With 10 fields per insert, there is a rough maximum of 200 inserts per query. I opted for 100 here just to be safe, but still performant.
=> fix: rebuild-tree exceeds mssql's parameter limit

server/modules/rendering/html-core/renderer.js
Telephone links will no longer be incorrectly parsed as web links.
Signed-off-by: Scott Simontis <yo@scottsimontis.io>
=> Fixes #1318

server/modules/rendering/html-security/renderer.js
The highlight feature in wysiwyg adds `<mark class="pen-red">`, but html security trips out the `class` attribute. This allows `class` and `style` for good measure, and chameleon coding.
=> fix: allow highlight color

client/components/editor/editor-ckeditor.vue
=> fix: light background in nested ckeditor unless dark mode

client/themes/default/scss/app.scss
In kinda response to: Requarks#1283 because i kinda like the fancy bullets so i propose a alternative solution that solves the problem with the list having issues with p elements and with multi lines but keeping the fancy css bullets.
Tested on Chrome, Firefox, Opera and Edge.
image of it working on chrome:
and image of it working on firefox:
I did not include screenshots of the other because i believe that showing this may be enough, but i can provide it if needed
I have 2 alternative css for the p like 
```scss
> p {
display:inline-table;
}
```
or
```scss
> p {
display:inline-flex;
}
```
i just choose to use 
```scss
> p {
display:inline-block;
vertical-align:top;
padding-top:0!important;
}
```
because i believe that it has more cross browser compatibility, but science for the other …
=> Fix list formatting multiline with fancy bullets

server/modules/storage/git/definition.yml, server/modules/storage/git/storage.js
Problem:
- Trying to use git storage feature with a private git server with ssh running on a non-default port.  Git over ssh typically happens on port 22 however non-standard setups can use a custom port number.  Wiki.js doesn't support adding custom SSH port while setting up the git storage.
Solution:
- Added an option on the git storage configuration page to allow specifying ssh port.  It is optional and empty by default with port 22 used by default if nothing specified.
Testing:
- Manually validated that the setting is properly picked up.
- Tested with custom and default ports and everything worked as expected.
Possible future improvement:
- Adding an advanced ssh section on the git storage page and rolling this configuration into that would be a possible way of simplifying the UI.
=> Adding an override for the ssh port

server/master.js
This applies the 1mb size limit to graphql by placing the body-parser statement prior to graphql.
=> fix: apply json size limit to graphql

server/core/config.js
Updates the location of "config.yml" from the old database type related location to the new "containers" location.
Related to #1533
=> fix: Update docker configuration file location

server/db/migrations/2.2.17.js
Missing quotes causes issues trying to migrate data.
h1.createdAt get parsed as h1.createdat casing the query to fail due to the column not being found.
=> fix: Correct Postgres 2.2.17 migration

package.json, server/modules/authentication/twitch/authentication.js, server/modules/authentication/twitch/definition.yml
The current Node module which is used for Twitch authentication hasn't been updated in a very long time. It's using the old method of obtaining user credentials. There is a new module, passport-twitch-oauth, which uses the correct endpoints. 
The scope requested has been updated for this new spec, and the profile image has moved location as well.
As for testing I confirmed by spinning up the docker image and testing the login locally.
=> fix: Resolve Twitch OAuth API - fixes #1268

server/modules/authentication/discord/authentication.js, server/modules/authentication/discord/definition.yml
Very small feature to optionally restrict discord authentication to members of a specific server. We use this in our wiki, maybe it could be useful to others.
=> Option to restrict Discord auth to a specific server

client/themes/default/scss/app.scss
This is fixing #898, #1602, and the list part of #1577.
No effects on other list features were found.
---
Markdown source and screenshot of render:
```markdown
- List item
- Indented list item
- Indented list item
- List item with long text.  List item with long text. List item with long text. List item with long text. List item with long text. List item with long text. List item with long text. 
- List item
- List item
- Indented list item
- Indented list item
- List item with long text.  List item with long text. List item with long text. List item with long text. List item with long text. List item with long text. List item with long text.[^fn1]
[^fn1]: The first footnote
- List item[^fn2]
[^fn2]: The second footnote with a longer text
1. List item
1. Indented list item
2. List item
- …
```
=> Fix rendering of unordered lists and footnotes

client/themes/default/scss/app.scss
This fixes copyright footer for printing related to issue #1593 , and probably fixes firefox print problem (#1034).
**Screenshot**
=> fix: media print css

server/models/pages.js
There is a bug mention at #1470. While the server tries to compare the page permission with the page rules, `page.sourceLocale` or `page.sourcePath` is not defined in the `page` object. The actual one must be `page.localeCode` and `page.path`. Otherwise, the `checkAccess()` function will compare `undefined` with page rules.
=> Fix #1470 move page failed with page rules

client/components/admin/admin-navigation.vue
Default link for new external link is now empty instead of '/'
fix #1747
=> Default link for new external link is now empty

client/components/editor/editor-modal-media.vue
This fixes editor-modal-media action button related to #1493 .
**Screenshot**
=> fix: editor-modal-media action button

package.json, yarn.lock
This fixes Japanese input problem related to #1774.
vuetify v2.2.23 has bug in VTextField for users using IME (Japanese, Chinese etc).
vuetifyjs/vuetify#11190
=> fix: VTextField for users using IME

client/themes/default/components/page.vue
Fixes #1230
Note: I assumed I could just add the `.assign-self-start` class like this, as it works for `lg3` and `xl2`.
=> make page TOC sticky

server/modules/rendering/html-core/definition.yml, server/modules/rendering/html-core/renderer.js, server/modules/rendering/html-security/renderer.js
Automatically adding rel noferrer or rel noopen to _blank target external links as recommended by the following reference.
https://developers.google.com/web/tools/lighthouse/audits/noopener
=> #1853: XSS attack fix 

client/themes/default/scss/app.scss
Bullets (I don't know, list markers? whatever) are at the left edge in both RTL and LTR mode and this line fixes it.
=> fix bullets position in rtl mode

server/modules/authentication/keycloak/authentication.js
In the Keycloak authentication module, the username (given by Keycloak) was used as the display name in wiki.js.
I propose to use the fullName given by Keycloak, with the username as fallback value.
=> use fullname from keycloak profile info with username as fallback

server/modules/rendering/markdown-kroki/definition.yml, server/modules/rendering/markdown-kroki/renderer.js
This pull request adds support for https://kroki.io/ that can be used to generate diagrams from many different kinds of formats. It can be used as a replacement of the already existing PlantUML renderer and many other formats like GraphViz, Nomnoml, Mermaid and others.
The implementation is based on the PlantUML renderer. There's an important difference in the way it can be used: in the first line of the diagram definition the selected format must be entered.
Markdown Example 1:
````
```kroki
mermaid
graph TD
A[ Anyone ] -->|Can help | B( Go to github.com/yuzutech/kroki )
B --> C{ How to contribute? }
C --> D[ Reporting bugs ]
C --> E[ Sharing ideas ]
C --> F[ Advocating ]
```
````
Markdown Example 2:
````
```kroki
plantuml
skinparam monochrome true
skinparam ranksep 20
skinparam dpi 150 …
=> Add Kroki renderer

dev/containers/docker-compose.yml
- Adds `container_name` fields for cli convenience
- Removes the `wikinet` network -- Compose creates a network automatically
- Bind-mounts selectively
- This fixes issues with the Git storage module in dev/docker mode. The issue is `/wiki/.git/` is bind mounted to the repo on the host, which interferes with the app's Git operations.
Let me know if you'd like me to rename commits (fix? feat?) or break it up into multiple PRs or anything like that.
=> Development docker-compose.yml improvements

server/models/storage.js
fix: #1604
exportAll action on s3 doesn't work.
The reason being that s3 handler is a class instance and not a plain object, thus when checking if the handler has the exportAll method, fails.
The fix is to use lodash `hasIn` which checks if a propery exists directly or inherited on an object.
I confirmed the fix locally ofcourse
=> fix: S3 Export all don't work #1604

client/components/editor/editor-markdown.vue
Fix #1692, where the width of the markdown editor and the preview increases relating to the word-length.
Apply `break-word` instead of `normal` for words in the editor, which allows words to be broken, if they get too long.
```css
.CodeMirror-wrap pre.CodeMirror-line, .CodeMirror-wrap pre.CodeMirror-line-like {
word-break: break-word;
}
```
Apply `break-word` to the `overflow-wrap` of the preview of the markdown editor, so long words do not overflow out of the screen to the right.
```css
.editor-markdown {
/* ... */
&-preview {
/* ... */
&-content {
/* ... */
p.line {
overflow-wrap: break-word; 
}
}
}
}
```
=> Fix #1692 : Properly wrap very long words in markdown editor

dev/helm/Chart.yaml, dev/templates/master.pug, dev/templates/setup.pug
Fix https://github.com/Requarks/wiki/issues/1958 "404 on android-icon-192x192" :
the existing filename is in fact android-chrome-192x192.png instead of android-icon-192x192.png
=> Fix #1958 404 on android-icon-192x192

client/components/admin/admin-security.vue, server/app/data.yml, server/graph/resolvers/site.js, server/graph/schemas/site.graphql, server/master.js, server/middlewares/security.js
Refactored Open Redirect vulnerability to allow for user configuration as requested.
Prior it was observed that the req.url could get parsed to navigate a user to an external website, example: https://docs.requarks.io////google.com// would navigate directly to google.com. This behavior was observed in the req.url variable. This PR allows a configurable middleware to strip all repeating / characters from the user controlled url. More about the vulnerability can be found at
https://cwe.mitre.org/data/definitions/601.html
In addition, it was observed that ./server/middlewares/secruity.js if statements were not referencing global variables correctly as per the ./server/app/data.yml file structure. As such they were effectively being ignored as confirmed by console.log statements. The data.yml …
=> Open Redirect Vulnerability Mitigation - CWE 601

dev/templates/legacy.pug, dev/templates/setup.pug
Fix https://github.com/Requarks/wiki/issues/1964 "404 on apple-touch-icon" : 
the existing filename apple-touch-icon.png is in fact in /favicons/ instead of /
=> Fix #1964 404 on apple-touch-icon

client/themes/default/components/page.vue
This issue is related to #1006 . The $vuetify.goTo() function expects a UTF-8 ev.target.hash . However, the markdown CRM URIencodes the ev.target.hash (this is great for browser compatibility, not so much for Vuetify)
Adding decodeURIComponent() to ev.target.hash fixes compatibility with Vuetify.
This fixes GitHub issue #1873
=> Make the links to subtitles work with special characters

client/themes/default/components/page.vue
This fixes garbled sidebar text. (fix #1971)
``atob()`` function has a Unicode Problem.
> The btoa() function takes a JavaScript string as a parameter. In JavaScript strings are represented using the UTF-16 character encoding: in this encoding, strings are represented as a sequence of 16-bit (2 byte) units. Every ASCII character fits into the first byte of one of these units, but **many other characters don't**.     -- from [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa)
**ScreenShot**
=> fix: sidebar base64 decode

client/themes/default/scss/app.scss
Implements the missing figure.image-style-align-right and figure.image-style-align-left css. Closes #1413.
=> Fix: Respect image floating from visual editor

server/modules/rendering/html-security/renderer.js
Fix: #2011
Reproduced the bug on master, and verified the fix
=> fix: secure html module removes target attribute from links #2011

server/modules/authentication/ldap/authentication.js
Signed-off-by: Jonas Jöst <jonas@gpplanet.de>
=> fixes #2050 use first email address when retrieving multiple from LDAP

server/core/auth.js
=> fix: tokenRenewal seems to be hard coded #1540

client/themes/default/components/nav-sidebar.vue
Issue:
When multiple locales are enabled the sidebar page-browser only shows the currently selected locale. This is correct behavior. However when a page-link is opened it tries to open it with the default locale.
Fix:
Include the locale in the graphql-query and insert it into the link. This way if the query changes to include other locales in the future, these links will also work.
Another approach would be to use the current locale to open the links, but this would close the possibility to include other locales in the sidebar browser in the future.
=> Fix: Include locale in nav-sidebar "browse-mode" links

server/models/pages.js
I have a local development instance using sqlite. After pulling the latest code, I receive errors while trying to load the website.
The reason is validation error for the page schema. 
This PR fixes the issue (current implementation sets js and css to be undefined in case extra is an empty object)
=> fix: page schema validation

server/modules/authentication/discord/authentication.js
Discord has updated their API endpoint due to a branding change. App developers are advised to begin updating integrations to prevent being affected by the breaking change which starts November 7th, 2020.
=> Change ‘discordapp.com’ to ‘discord.com’

server/models/pages.js
Move behavior of `reconnectLinks` was replacing
```
<a href="old-path" class="invalid">
```
with 
```
<a href="new-path" class="valid">
```
but we know that before the move we have valid links like
```
<a href="old-path" class="valid">
```
Another necessary change was that if a page is moved from `old-path` to `new-path` we have to do something more than this. We may have invalid links to the new path, like
```
<a href="new-path" class="invalid">
```
which they shall be valid now.
And this is the same process that is done in page creation.
This fixes #1990
=> Change reconnectLink behavior for page move

server/modules/storage/git/storage.js
Hi, 
based on this issue https://github.com/Requarks/wiki/issues/2114 I noticed that the user object was not passed to the WIKI.models.pages.deletePage function, so when a page was deleted on the git repository the error was reported with user: "undefined" .
=> fix: user "undefined" error on deletePage by git storage

client/components/editor/editor-markdown.vue, package.json, server/modules/rendering/markdown-multi-table/definition.yml, server/modules/rendering/markdown-multi-table/renderer.js, yarn.lock
=> feat: Support MultiMarkdown tables #2125

server/graph/resolvers/page.js
fixes: #1884
Tags retrieval and search will always return all tags, regardless of what the user is allowed to see.
This PR fixes this issue.
- Tags that are not associated to any pages will never be returned! Not sure what is the right course of action here - should we always return those orphan tags? If we do than that might impose a security leak...
- This makes the queries a bit slower as we need to get the pages first so we can filter by access
- We can't impose the search result size limit in the query itself as we can receive many duplicates, so we have to get all the tags and then extract the first 5 results. I thought about reversing the query to get the tags and join with the pages, but then if we ask for top 5 we might remove some of them due to access restrictions and we will …
=> fix: tags are not filtered by access #1884

dev/helm/README.md
A few of the defaults listed in the README are out of sync with what is in values.yaml
=> Updated README config table defaults to match values.yaml

dev/helm/Chart.yaml
The postgresql chart in the stable repository has been [deprecated](https://github.com/helm/charts/tree/master/stable/postgresql#this-helm-chart-is-deprecated).
Updated the dependency to point to the new chart at [bitnami/charts](https://github.com/bitnami/charts/).
=> misc: update postgresql chart dependency

server/models/assets.js, server/models/storage.js, server/modules/storage/azure/storage.js, server/modules/storage/box/storage.js, server/modules/storage/disk/storage.js, server/modules/storage/dropbox/storage.js, server/modules/storage/gdrive/storage.js, server/modules/storage/git/storage.js, server/modules/storage/onedrive/storage.js, server/modules/storage/s3/common.js, server/modules/storage/sftp/storage.js
fix: #2074
Backstory - I uploaded a large 100mb mp4 video as an asset (using postgres as the db) and added an html5 video element to play it in a page. As soon as the page was trying to load, my wiki server just stopped responding for a good few minutes. Cpu was spiking at 100%.
After a lot of investigation, I came to realize that the issue occurs due to a performance bug in the `node-postgress` library. I already fixed [the bug](https://github.com/brianc/node-postgres/pull/2241) ~~and waiting for CR on it.~~ and it was released and it is already being used in the master branch.
This PR fixes a performance issue while handling videos:
When a request is aborted (due to change of playing position for example) the browser cancels the request, but the error handling in the code ignored it and …
=> bug: playing a video from assets is super slow #2074

dev/helm/templates/_helpers.tpl
When you use a release name in the helm install command the postgresql secret name was mismatched as it uses the Chart name and not the Release name.
=> Align secret name

dev/helm/templates/service.yaml, dev/helm/values.yaml
Changed target branch to dev, sorry.
=> feat: modify helm chart for extended service features

dev/build/config.yml
I would like to add an additional configuration switch to the docker build to enable switching to offline mode via environment variable.
If the pull request is accepted, I will add a pull request to the documentation.
Refers to #1956
=> Add configuration switch "OFFLINE" to docker configuration

client/components/common/search-results.vue
All search results were not visible on desktop screens beyond the viewport height, adding overflow-y: scroll fixes this
=> Add overflow scroll to search results

dev/helm/Chart.lock
Previous version of Postgresql required userid 0 for init container
=> Upgrade Postgresql dependency to run in non root

.github/CONTRIBUTING.md
When clicking the image under contributors in the [CONTRIBUTING.MD](https://github.com/Requarks/wiki/blob/dev/.github/CONTRIBUTING.md) file you are taken to the following link which results in a 404 https://github.com/Requarks/wiki/blob/dev/.github/graphs/contributors
This is due to the fact a relative path is used. This change replaces this with the direct link, which is consistent with the approach taken in the README.
=> Fix broken contributors link in CONTRIBUTING.MD

server/helpers/page.js, server/modules/storage/azure/storage.js, server/modules/storage/disk/storage.js, server/modules/storage/git/storage.js, server/modules/storage/s3/common.js, server/modules/storage/sftp/storage.js, server/test/helpers/page.test.js
Hello all !
We're using wiki js as an internal tool, and we enjoy it :slightly_smiling_face:  We're making good use of the storage plugin to backup created articles in a github repository and them use it as a source for our blog. That is, we're missing a critical information, that we believe should be exported when creating pages in the storage: the creation date.
This PR also fixes the jest tests for the `injectPageMetadata` helper, which were broken.
Thank you for your time !
=> feat: export creation date in dumped content

client/components/admin/admin-locale.vue
This fixes invisible download button in admin locale page. (fix #2170)
**Screenshot**
=> fix: invisible download button in admin locale page

server/graph/resolvers/page.js, server/modules/search/db/engine.js
**Description**
This code will allow the "search" component to correctly filter pages by usergroup permissions based on tags instead of paths
Partially handling issue: https://github.com/Requarks/wiki/issues/2211
**Steps to reproduce the behavior**
1. Create a usegroup which can access **only** pages with the **tag** "public"
2. Create a page **without** tags or any tag except "public"
3. Create a page **with** at least the tag "public"
4. Search for the pages
If you don't have the following code you won't be able to see any result when being a part of the just created usergroup.
Otherwise you will correctly get the access to the page **with** at least the tag "public"
**Host Info (please complete the following information):**
- OS: Docker
- Wiki.js version: 2.5.16
- Database engine: …
=> "Search" supporting usergroup permissions by tags

client/components/editor/editor-markdown.vue
Fix for #2062. Using token.string only captured the character at the cursor. Now using the cursor location to determine suitable search text. Also corrected syntax issue where suggestion removed opening link parenthesis.
=> fix: markdown editor URL autocompletion

server/modules/analytics/matomo/code.yml, server/modules/analytics/matomo/definition.yml
This pull request fixes #2525 by merging the upstream changes to Matomo's tracking script into the integration in WikiJS.
**Example tracking script generated by WikiJS with this PR**
```html
<script type="text/javascript">
var _paq = window._paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
var u="https://matomo.datahoarder.dev/";
_paq.push(['setTrackerUrl', u+'matomo.php']);
_paq.push(['setSiteId', '2']);
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
</script>
<noscript><p><img …
```
=> Merge upstream changes into Matomo integration

server/models/users.js
In our setup (based on yunohost) the profile.email field could be either a string (and that was properly handled) or an array.
This code adds support for the case where it is an array.
=> Add a valid case for primaryEmail

client/components/comments.vue
The i18n var `common:action.cancel` is correctly `common:action*s*.cancel`.
ref: https://github.com/Requarks/wiki-localization/search?q=common:actions.cancel
=> bugfix: Fix var name

dev/helm/README.md
The ingress.hostname entry listed in the README is erroneous and not used in the ingress.yaml file.
This change corrects the documentation to refer to ingress.hosts and list the default value as given in values.yaml.
=> docs: Correct ingress.hosts in README

client/components/editor/common/katex.js
When using inline math (`$e^{-x^2}$`) the curly braces are interpreted as attributes by [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs). Since most of the times they are not valid attributes they simply get removed.
This patch escapes the curly braces (the default attribute delimiter), fixing the KaTeX rendering errors.
The problem occurs only when the inline math ends with a _curly brace block_ (see examples below). For this reason the third example below works also in the current version.
An alternative fix may have been to force the math block not to end with the curly braces, for example by adding some spacing (e.g. `\,`). I preferred not adding some spurious spaces, the escaping strategy should be pretty invisible.
One could think it should be enough to escape the …
=> fix: inline math interpreted as attributes

server/modules/rendering/markdown-supsub/definition.yml
Fix spelling of superscript in definition file for subscript/superscript rendering module. ("supercript" -> "superscript")
=> Fix minor misspelling in Subscript/Superscript rendering module

server/modules/authentication/azure/authentication.js, server/modules/authentication/azure/definition.yml
This adds cookieEncryptionKeyString configuration in the Azure AD authentication module.  It represents an array of cookie encryption strings and enables workaround for SameSite cookies.
See [the passport-azure-ad doc](https://github.com/AzureAD/passport-azure-ad#41-oidcstrategy) about new `OIDCStrategy` options: `cookieSameSite`, `useCookieInsteadOfSession`, `cookieEncryptionKeys`.  It's not mentioned in the doc that `cookieSameSite` won't work without `useCookieInsteadOfSession` or without `cookieEncryptionKeys`.
When enabled, it returns a short-lived cookie with `Secure; SameSite=None` during Azure AD OpenID Connect authentication attempts.
Unfortunately there's no unit test because I'm not familiar with auth module testing.  And it's missing the way to add this to existing Azure AD …
=> Enable passport-azure-ad workaround for SameSite cookies

server/core/mail.js
Prepends the wiki site URL to the logo path used when sending email from the wiki.
Before: `<img src="/uploads/logo.png"`
After: `<img src="http://wiki.site.url/uploads/logo.png`
=> fix: use absolute URL for logo in email

server/modules/search/elasticsearch/definition.yml, server/modules/search/elasticsearch/engine.js
For better search results especially in Chinese, which the standard token analyzer may not work well. In Chinese, the adminstrator may need to set the token analyzer to smartcn, itk, etc. This PR adds the elastic analyzer configuration to the search module.
=> Feature: Custom configuration for elasticsearch

server/models/pages.js
For building suggest in elasticsearch, the safeContent field will be splitted into arrays. If the page is renamed or moved, the server will throw error: "Cannot read property 'split' of Undefined", and the index will be broken. Here two lines are added to fix this issue.
=> Fix: Search engine broken when renaming or moving pages

client/components/tags.vue
See #2743
Initial state : Create a "Home" page having two tags "hé hé hé" and "hello world". Navigate to view that page.
=> Support tags containing special characters

server/core/db.js
If in server config mysql has autocommit = 0, then wikijs fails with locks like this:
```
2020-10-30T12:56:51.725Z [JOB] error: Rebuilding page tree: [ FAILED ]
2020-10-30T12:56:51.726Z [JOB] error: truncate `pageTree` - Lock wait timeout exceeded; try restarting transaction
```
=> Set autocommit for mysql

server/modules/storage/disk/storage.js, server/modules/storage/git/storage.js
At `pageHelper.injectPageMetadata` references `editorKey` and `tags` to build metadata, but this data seems not to be supplied to this function, since page object is only built from specified columns.
As a result, tags are always empty when exporting pages, and editor key appears as undefined.
It happens also with git storage, but it may also happen with another storage providers.
I run into this issue running Wiki.js 2.5.170 with the following Docker stack:
```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                         NAMES
39373979b693        requarks/wiki:2                         "docker-entrypoint.s…"   44 minutes ago      Up 9 minutes        0.0.0.0:80->3000/tcp, …
```
=> Update storage.js to match pageHelper.injectPageMetadata

server/jobs/rebuild-tree.js
See https://github.com/Requarks/wiki/issues/1503 and https://github.com/Requarks/wiki/issues/2553
When the total page number is large enough (usually about 80+), sqlite will throw error: "Too many variables". This commit reduces the chunk size for sqlite configuration.
=> Fix: Rebuilding tree error when the page number is large enough in sqlite

client/components/admin/admin-groups-edit-rules.vue
Fix: In group edit rules, write scripts permission and write styles permission can be configured.
At present, the user that are not in the administrator group have no access to edit scripts and styles in page editor panel. This commit add configuration in group rule manage webpage so that users' permission on writing styles and writing scripts can be modified.
=> Fix: In group edit rules, write scripts permission and write styles permission can be configured.

server/modules/authentication/ldap/authentication.js
Fixes #2624
We avoid reading the `tlsCertPath` property if it is not needed. 
`tlsEnabled`: true, `verifyTLSCertificate`: true => read `tlsCertPath`
`tlsEnabled`: true, `verifyTLSCertificate`: true, `tlsCertPath`: `''` => __do not__ `fs.readFileSync(conf.tlsCertPath)`
`tlsEnabled`: true, `verifyTLSCertificate`: false => __do not__ `fs.readFileSync(conf.tlsCertPath)`
`tlsEnabled`: false `verifyTLSCertificate`: false => __do not__ `fs.readFileSync(conf.tlsCertPath)`
=> fix: LDAP: avoid reading empty tls cert file

server/graph/resolvers/storage.js
This fix issue #2443 (and maybe partially #1158)
When updating a sync interval, the value is updated in database however, the client display always the default time (e.g. 5 min with git storage). The fix simply gets_syncInterval_ value from the model rather than the module data storage.
=> fix: get syncInterval from model not module data

server/jobs/rebuild-tree.js
Fixes #2995 which was caused by a syntax error introduced in `rebuild-tree.js`.
=> Fix #2995 - syntax error in rebuild-tree.js

server/middlewares/security.js
Wiki.js uses the wrong property to access the saved value for the max-age field of the Strict-Transport-Security HTTP response header. After enabling the "Enforce HSTS" option in the administration area, under the "Security" section, One would expect a new HTTP response header to be set like:
`Strict-Transport-Security: max-age=600; includeSubDomains`
Instead, this header is set:
`Strict-Transport-Security: max-age=undefined; includeSubDomains`
This is invalid according to [RFC 6797](https://tools.ietf.org/html/rfc6797#section-6.1.1) and we cannot expect browsers to correctly apply the intended HSTS policy.
This PR fixes this.
I have tested this change with the current dev branch on one of my servers and it's working.
=> Fix HSTS header max-age value.

server/controllers/auth.js
For the local authentication strategy the loginRedirect cookie is read in login.vue and will redirect the user to the page they requested before needing to login. If you aren't using the local authentication strategy, but instead are using a different strategy, like OpenID Connect etc then logins aren't redirected back to the desired location. Fix this so behavior is the same whether using the local strategy or a different one. Fix based on what is done in login.vue.
=> fix: loginRedirect doesn't work for non local strategies

server/modules/storage/s3/common.js
Currently, upon moving/renaming files in wiki with AWS S3 storage setup, we get `Access Denied`/`Invalid object key` errors from AWS.
- As specified in [S3 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property), the `copyObject` method requires the `CopySource` field to supply the bucket name in the path. 
- As such I have prepend the `bucketName` to `CopySource` fields. 
Let me know if this change is OK. I can make any change necessary to follow the repo's guidance.
=> Fix S3 copyObject usage - Missing bucket name

server/core/asar.js, server/core/kernel.js, server/core/scheduler.js, server/index.js
There is a graceful shutdown procedure written in the kernel, but not registered with the process exit handler.
This change adds:
- a SIGINT handler,
- a PM2 specific message handler on windows platform,
- and properly shutdown the scheduler and wait for running jobs to complete before exiting.
=> fix: graceful shutdown

dev/helm/README.md
Small doc improvements:
- Add the 2 missing parameters `postgresql.existingSecret` and `postgresql.existingSecretKey` in the list.
- Update the **"Using an external PostgreSQL server"** part by specifying how to use an existing postgresql Secret
=> Improve Helm README (existing postgresql Secret)

server/modules/authentication/google/authentication.js, server/modules/authentication/google/definition.yml
Similar to #608, I'm adding support of hd / hostedDomain functionality to the google auth module. The setting is needed to enable the account selection UI optimization when limiting the authentication to the company domain.
For additional info: https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters
Note: I'm not a JS developer so please check the code after me.
=> Add support of `hd` google auth parameter - to work with G Suite domains

dev/helm/Chart.yaml, dev/helm/templates/deployment.yaml, dev/helm/values.yaml
It adds the ability to completely customize the liveness probe and readiness probe of the wikijs deployment in the helm chart.
The actual configuration DOES NOT change the probes defined before : users who do not care about this change won't notice anything.
I opened this PR because when I deployed wikijs via helm, after install the pod was crashlooping because it was too slow to start, and the probe keep restarting it, so I looked for more customizations of the probe and I got none, so I decided to make it myself and share it.
The two files changed are the deployment of wikijs : dev/helm/templates/deployment.yaml and the default values file in dev/helm/values.yaml
Using `helm template .` renders the same deployment as before the change, so I think it does not break anything.
Step to …
=> feat(helm): adding liveness and readiness probes customizations 

package.json, server/modules/authentication/slack/authentication.js, yarn.lock
This commit replaces the observably defunct @aoberoi/passport-slack
implementation with that of nmaves's passport-slack-oauth2
I have (manually) tested this on a local installation to verify it does correctly work with a slack + wiki.js installation.
=> Slack Auth fix: replace passport-slack implementation

server/models/pages.js, server/modules/storage/git/storage.js
Currently, the git storage model [does not handle files being renamed](https://github.com/Requarks/wiki/discussions/3707). This PR implements this by noticing when a filename in a diff contains ` => ` and relocating the corresponding page.
=> git storage: handle relocated files

client/components/admin/admin-pages.vue
=> fix: resolve admin pages pagination bug

server/modules/storage/sftp/storage.js
when the dir exists, sftp.mkdir() would raise an error and ends the for loop.
fix #2297
=> fix sftp error

server/modules/authentication/rocketchat/authentication.js
As mentioned in #2572, Wiki.js uses the wrong property to access a users' E-Mail address in the Rocket.Chat auth module.
This PR fixes this.
I have tested this change with the current `dev` branch on one of my servers and it's working.
Rocket.Chat's response contains an array containing all the emails a user has added to Rocket.Chat. The currently used property `email` does not exist in the response. Please see https://docs.rocket.chat/api/rest-api/methods/authentication/me.
**Since we have no option to choose  which E-Mail to use for the OAuth mechanism, I just assumed, we take the first one in the array and go for it.**
Please tell me, if you are OK with this, since it can be considered as a dirty hack. 
I can add some validation that checks, if the array is empty that throws an error …
=> Fix Rocket.Chat auth module

client/themes/default/scss/app.scss
On mobile devices, too long summaries for spoilers overflows this spoiler in height. Managed to fix this by removing the `height` CSS property, changing the display mode to `list-item`, and adding vertical padding for `<summary>` tag.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
P.S. Also accidentally fixed that triangle absence on Firefox.
=> fix: spoiler summary overflows it's parent

client/themes/default/scss/app.scss
Cleaning up Headers within Details Summary to fix an issue with display.
Modified app.scss with the following changes:
- Remove top-margin and keyline under all headers within a Details **Summary**
- Make all Headers within a Details Summary 100% width to fix TOC Anchor location issue.
Let me know if there's anything else I should consider here.
Screenshot fixed:
=> Fix display of Headers within Details Summary

server/modules/rendering/html-core/renderer.js
This simple PR fixes the issue where TOC Links fail to work for headers that have been given a custom ID, or when defined in the HTML body as discussed in #3502 
Such as in the scenario below, where Wiki.js will fail to properly generate the page TOC for Header 1
```md
[Link](#custom)
```
=> TOC Links and Custom Header ID Fix

client/themes/default/scss/app.scss
Since we're provided base styles to work "out of the box", we should consider edge cases such as this where footnotes always show their own keyline, even when preceded by a Header (which is styled with a keyline underneath)
This PR hides key-lines created by `markdown-it-footnote` template when footnotes are directly preceded by header, but leaves them in place when the footnotes follow regular Phrasing content.
Examples:
```md
[^1]: Shows no key-line because References header has one already
Text goes here and whatever else
[^1]: these footnotes are not directly preceded by a header, but a paragraph and WILL show a key-line
```
=> Hide footnotes keyline when preceded by header

dev/helm/README.md
ca certificate for database connection is not a path, but certificate content
=> doc: fix typo on helm documentation

client/themes/default/scss/app.scss
It adds the ability to automatically enable scrollbars when a DrawIO diagram width is higher than the browser/screen width. 
We have documentation with complex diagrams, that are sometimes very big.
Unfortunately, the access to these diagram is today unusable, beacause a part of them is not displayed. The reason is that their size is not adapted to the browser/screen size OR a scrollbar is not enabled. 
I have decided to suggest this small fix (a new field in the CSS class .diagram) as it is a simple workaround enabling scrollbars.
You can test the change locally in your web browser by editting dynamically your CSS class or inject directly the CSS code in the Theme section of the admin page:
```css
.diagram {
overflow: auto
}
```
=> Add scrollbar for big diagrams

dev/helm/README.md, dev/helm/templates/deployment.yaml, dev/helm/values.yaml
This PR aims at making possible to add extra volumes and extra volumes mounts in Wiki.js container. It is really useful to add CA certificates in /etc/ssl/certs for instance.
Deploy the chart with these values and check the mount in the Wiki.js container.
```yaml
[...]
volumeMounts:
- name: my-volume
mountPath: /mydir
readOnly: true
volumes:
- name: my-volume
hostPath:
path: /mydir
```
=> Introduce volumes and volumeMounts chart values

client/themes/default/components/nav-footer.vue, server/graph/resolvers/site.js
Solution:
Change the if condition, so instead of checking for the property directly, Checking using "hasOwnProperty" method.
Please associate this PR with issue #5164
=> #5164 Administrator general setting is not saving with empty value.

server/modules/authentication/oauth2/authentication.js, server/modules/authentication/oauth2/definition.yml
See https://github.com/requarks/wiki/discussions/5187
Small patch for using older OAuth2 authorization servers
=> feat(auth): OAuth2 access_token in GET query string in userInfoURL

server/modules/storage/git/storage.js
git has the quotopath option enabled by default, filepaths with unicode characters will be escaped, causing the wiki to not handle changes.
As shown below, the changed file is the Chinese file name "你好"
=> fix: git storage does not sync files with unicode

client/components/admin/admin-users-edit.vue, client/components/profile/profile.vue
Kiev is a Russian style of spelling. The proper and government official way is Kyv.
More details is available [there](https://en.wikipedia.org/wiki/KyivNotKiev).
=> fix: changed spelling of Kiev to Kyiv

package.json, server/modules/authentication/twitch/authentication.js, yarn.lock
This fixes the Twitch auth strategy which currently displays "Oops, something went wrong...Failed to fetch user profile" when users attempt to authenticate. 
On May 1 2021, [Twitch began requiring a "Client-Id" header for all Helix API calls](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916). The current Twitch passport strategy package (`passport-twitch-oauth`) has not been updated to account for this, thus its `/users` call to the Twitch API always fails. 
Code in question: https://github.com/mattgaunt/passport-twitch/blob/master/lib/strategy.js#L75-L76
Given the `passport-twitch-oauth` package has not received any updates for 4 years since it's initial 1.0 release, I opted to move to a more maintained package instead of trying to submit a fix to the …
=> fix: users unable to authenticate with twitch auth

server/modules/authentication/saml/authentication.js
This fixes
this.options.authnContext.forEach is not a function
when trying to login via SAML on wiki-js 2.5.281.
Reason for that is that `authnContext` must be a list now which is
apparently a breaking change that was missed while upgrading
passport-saml[1].
Resolves #5289
[1] https://github.com/node-saml/passport-saml/pull/615
cc @NGPixel
=> saml auth: `authnContext` must be a list now

client/components/common/search-results.vue
When clearing the search keyword and re-input, the search results are display as empty
After modifying response.result, the value is always the empty.
It maybe related to the apollo client result cache, response.result cannot be
modified.
=> fix: search result display as empty

server/modules/storage/git/storage.js
This was an edge case we ran into wanting to keep internal documentation off our synced git storage. This change allows us to maintain our own gitignore file to exclude files from git storage and still sync them to other storage backends.
=> fix: don't push files to git if ignored

dev/helm/templates/deployment.yaml, dev/helm/values.yaml
I could not seem to get around the self signed easily. this works perhaps 2 would be better but I could not get it to work even when passed as a string without the head/footer
https://gist.github.com/zmts/f3306945e90914c4dedda5e0eaf1a279#solution-2
Added
feat: startup probe
at any rate this will work with DO connection string with the change of sslmode=require to ssl=true. could handle but likely a note is sufficient or maybe os obvious.
=> feat: allow self-signed ssl

server/modules/search/elasticsearch/definition.yml, server/modules/search/elasticsearch/engine.js
I added ssl options for elasticsearch. This allows the use of elasticsearch with self signed certificates.
=> feat: add elasticsearch ssl options

client/components/common/search-results.vue
I originally opened the same request on a now deleted account, and will submit pull requests from this account instead - thank you for your understanding. 
**fix: page cursor position stays the same between page selection**
Given a query with multiple result pages, if the cursor is moved to a result entry, then the user selects a different page, the cursor remains on the previous position.
**fix: search results not displaying on first page**
Given a query with multiple result pages, if a certain page is selected, then another query (with the same or more result pages as the previous entry) is searched, the results will display on the previously selected page.
=> Fix page cursor and pagination

server/modules/authentication/auth0/authentication.js
Currently the Auth0 authentication module doesn't log users out of auth0, so if they choose Auth0 again, they'll already be logged in.
This adds a logout func to the Auth0 authentication module so that users are fully logged out on logout.
=> Add logout for auth0

server/modules/storage/azure/definition.yml
=> fix: Correct typo for hint under actions section

server/modules/authentication/oidc/authentication.js, server/modules/authentication/oidc/definition.yml
This is a first try at getting oidc groups to work
=> feat: Set groups based on OIDC

dev/helm/templates/service.yaml, dev/helm/values.yaml
Hello!
When service.type is LoadBarancer, Made it possible to specify the IPAddress.
Please check it. 😃
=> add loadBalancerIP param in helmchart

server/modules/authentication/oidc/authentication.js
The changes in v2.5.288 doesn't seem to be tested well. We use Keycloak via OIDC (because we need a group mapping which is absent in Keycloak provider) so I fixed it right in prod (yeah it's sort of things we always love). Sending a PR, hope the fix works for others.
1. `await user.$relatedQuery('groups').select('groups.id')` already returns a groups array, not an object with `groups` property.
2. unrelate() should be used with a where clause
=> fix map() call on undefined; fix unrelate() usage

server/modules/authentication/keycloak/authentication.js, server/modules/authentication/keycloak/definition.yml
Login failed after updating Keycloak to version 20.0.
Wiki.js showed the "Ooops, somethin went wrong" screen without any error details and Keycloak logged a unauthorized request to the `userinfo` resource.
A default `access_token` requested with an empty scope list may no longer get the OpenID user information. We can enable this by explicitly setting the scope to `openid email profile` to get the required data.
This issue was also described by @aurorasmiles  here: https://github.com/requarks/wiki/discussions/5805
=> Fix login with Keycloak 20 by explicit set OAuth scopes

client/components/editor/editor-markdown.vue, server/modules/rendering/markdown-katex/renderer.js
This PR allows user to define [macros](https://katex.org/docs/supported.html#macros) that persist over the page with the [`\gdef`](https://en.wikibooks.org/wiki/TeX/gdef) command.
Reference: https://katex.org/docs/api.html#persistent-macros
=> Feature: KaTeX persistent macro support

server/modules/comments/artalk/code.yml, server/modules/comments/artalk/definition.yml
This module integrates [Artalk](https://artalk.js.org), a self-hosted comment system to the comment section.
=> feat: add artalk comment module

server/modules/storage/git/storage.js
The git storage module will encounter an error when a file with the same branch name exists in the root directory of the repo.
```
fatal: ambiguous argument 'branch_name': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
This pull request will fix the problem by adding `--` after the `this.config.branch` param of  the `git log` command.
=> fix: `git log` should explicitly separate branch from paths

server/core/sideloader.js
We have a setup with kubernetes where external communication is not allowed. So our solution for localization was to use the offline mode and build a custom image from the base Wiki.js image, where we preload the localization files during the build process of the image. This way works fine, but in the admin ui we can not see the availability of each locale because this information would normally be loaded from the GraphQL endpoint which is of course blocked in our environment.
Our approach currently loads the localization files at the build time of the docker image from the GraphQL endpoint, but the sideloader doesn't support importing the availabilities from the locales. So maybe this extension of the sideloader would be helpful for others who have the same problem.
=> feat: sideloader can import availabilities

server/modules/storage/git/storage.js
If Git's `color.ui` has been set to "always" globally, the git storage module will fail to sync because `branches.all` will contain "\u001b[31mremotes/origin/master\u001b[m" instead of "remotes/origin/master", as revealed by `WIKI.logger.info(JSON.stringify(branches.all[0]))`.
=> git storage: disable color.ui

server/modules/authentication/oauth2/authentication.js
This PR enables the state key on the generic oauth2 requests. The state key is more secure and is required by a lot of oauth2 providers such as Authelia. https://www.rfc-editor.org/rfc/rfc6819#section-4.4.1.8
A working config for Authelia. (What I used to test this patch)
```yaml
- id: Wikijs # this should be changed to something more secure
description: Wikijs SSO
secret: '' # Long randomly generated string
public: false
authorization_policy: one_factor
audience: []
scopes:
- openid
- profile
- email
redirect_uris:
- https://wiki.example.com/login/{UNIQUE_ID}/callback # Copy this from the bottom of the oauth2 setup in wikijs
userinfo_signing_algorithm: none
grant_types:
- authorization_code
```
If you are using Authelia's file database
```yaml
user:
disabled: false
displayname: "User" …
```
=> Enable state key on generic oauth2

server/modules/authentication/oidc/authentication.js, server/modules/authentication/oidc/definition.yml
I noticed when setting up the oidc authentication method, that it just uses the first part of the email (for my oidc provider authentik). In parallel to the oauth module I added the option to change the claim for the displayName so it can be set manually.
=> Adds displayName property to oidc authentication method

server/graph/resolvers/page.js, server/graph/schemas/page.graphql
adding a user friendly of getting a page. If I want to get find a page by text, I have to do 2 query. One for the id and then using single.
=> feat: add singleByPath for page query

server/modules/authentication/ldap/authentication.js, server/modules/authentication/ldap/definition.yml
This PR provides LDAP group mapping functionality similar to the OIDC group mapping. Thank you to @fionera for the OIDC groups functionality, that provided the roadmap for us to get LDAP group sync to work.
=> feat: Set groups based on LDAP groups

server/core/db.js, server/models/pages.js, server/modules/storage/disk/storage.js, server/modules/storage/git/storage.js
I've discovered that my implementation of handling moved or renamed files for git storage in #4307 was incomplete. It turns out that if the old and new file paths have common elements, `git diff --stat -M <hash-before> <hash-after>` (called by `this.git.diffSummary`) will display them in a compressed format using braces. This commit updates the logic to handle all the non-renaming, simple renaming, and compressed renaming formats that I was able to find. Examples are below:
```
// edit top level file
file.md
// rename top level file
file.md => index.md
// move file to folder
index.md => folder/index.md
// rename folder, or move file between folders
{folder => directory}/index.md
// rename file in folder
directory/{index.md => subindex.md}
// move file to subfolder
directory/{ => …
```
=> git storage: handle file renames between folders

server/modules/authentication/oidc/authentication.js
Relates to: https://github.com/requarks/wiki/pull/6096
=> Fixes setting displayName from OIDC

server/controllers/common.js
When requesting a page without an explicit locale, the server will redirect to a locale specific page. However, the redirect drops the query parameters on the original request. It would be nice to retain the query parameters. We have a page that has some JS to further redirect someone to a more specific page. Currently this only works when the original request goes to a page with an explicit locale.
=> feat: include query parameters in locale redirect

client/themes/default/scss/app.scss
To follow up on PR #5895, and discussion #5894, I propose this little modification to not impact the inline code.
The goal is to apply the style only if `code` doesn't have a class whose name starts with "language-" which is the case as soon as you use a code block. Inline code does not use a language-* class.
Sorry for my English.
=> fix: code style in blockquote

dev/helm/README.md, dev/helm/templates/deployment.yaml, dev/helm/values.yaml
We have the keycloak instance signed with our internal CA and I do not like disabling of certs trusting. So we just need to append extra CA certs.
=> Allows setting the NODE_EXTRA_CA_CERTS variable

server/models/authentication.js
This pull request should fix an existing authentication strategy not getting new properties after an update. It does this by using the existing function to pull in new properties and their defaults, and if any new properties are detected, write the strategy back to the database with the new defaults.
Something of note, a bad auth strategy update that includes breaking default properties can break an installation, so people need to keep this in mind if this PR is merged.
=> Fix existing auth strategies not getting new props

server/modules/authentication/oidc/authentication.js, server/modules/authentication/oidc/definition.yml
This pull request adds a new option "skip user profile" to the settings for the Generic OpenID Connect / Oauth2 authentication. The default is false. This exposes the option to skipUserProfile which is configurable in the underlying library that WikiJS uses: passport-openidconnect
The advantage of having this option is so that we can integrate with CIAM (customer identity access management) solutions such as Azure AD B2C which do NOT have the UserInfo endpoint as default.
Furthermore, it seems that WikiJS does not actually use the UserInfo endpoint for anything, as the Display name is taken from the email claim.
The change has been tested with Azure AD B2C and works well. NOTE: A custom policy is still required on this platform in order to return the "email" claim!
=> Add skipUserProfile option for Generic OpenID Connect / OAuth2 Authentication

client/themes/default/scss/app.scss
Hello. 
Editing in a private wiki, I try to use images to be part of a list, the issue is that those got aligned with the text, so I tested with the css to fix it. I also thought to change it with `display:block;`, but if there's a reason to use inline-block for this, this change still will respect that and fix this issue. I include this tests images.
Before:
After:
=> [Fix] List paragraphs inline 100%, image into lists

server/modules/authentication/gitlab/authentication.js, server/modules/authentication/gitlab/definition.yml
In some setups, self-hosting GitLab will require a different auth or tokenUrl than the baseUrl used to redirect the user to approve access. For example, there may be a firewall blocking WikiJS from accessing GitLab on the same server using the public baseUrl. This is the root of the problem I was facing here: https://github.com/requarks/wiki/discussions/6377 .
This PR adds `authorizationURL` and `tokenURL` as configuration options for the GitLab authentication strategy. This allows the baseUrl to be set to redirect the user for approval, but have WikiJS use an internal tokenURL for validation. These new options may be left empty and they will be calculated from baseUrl the way they currently are. This is a non-breaking change.
=> Allow custom GitLab endpoints for self-hosting

server/controllers/ssl.js
HTTPS redirection rebuilds the full URL using `req.originalUrl`, which includes query parameters (see the
[express docs](https://expressjs.com/en/api.html#req.originalUrl)). Prior to this patch, appending the stringified query params to `req.originalUrl` resulted in duplicate parameters, e.g.
`wiki.js/callback?session=123&code=abc?session=123&code=abc`
which caused errors when being redirected from an insecure (http://) callback URL to a secure version when using Keycloak auth.
This issue is probably rare, but in cases where HTTPS redirection is enabled and a user tries to hit an insecure URL with query parameters, it could cause problems.
=> Remove duplicate query parameters on HTTPS redirect

server/modules/analytics/umami/definition.yml, server/modules/analytics/umami2/code.yml, server/modules/analytics/umami2/definition.yml
According to the discussion results of [PR#6412](https://github.com/requarks/wiki/pull/6412), I have created a module with ID `umami2` in this PR to adapt to the breaking changes of Umami, and accordingly updated the name of the original Umami module.
=> feat: update title of analytics module umami

server/modules/storage/git/storage.js
This PR should resolve #5074 (or at the very list make the likelyhood of it occurring much less).
The underlying simple-git library defaults maxConcurrentProcesses to 5. This creates problems when multiple tasks run needing to acquire the git lock file (add, commit, etc..).
By changing this value to 1, simple-git will now manage the queue of commands internally, running one at a time.
Before this change, i could upload 3 ~800kb jpgs and almost 100% of the time get a git error on 2 of the git add steps. This would eventually then lead to a git syncing error with the storage module.
Post this change, I could no longer reproduce the error.
There is likely a side effect of git actions take a bit longer on startup and if multiple page saves are happening simultaneously. Those tend to happen …
=> fix(git): Reduce concurrency to avoid lock file conflicts.

package.json, server/modules/rendering/markdown-pivot-table/definition.yml, server/modules/rendering/markdown-pivot-table/renderer.js
Adding the [`markdown-it-pivot-table`](https://www.npmjs.com/package/markdown-it-pivot-table)  plugin to the list of rendering modules in wikijs.
It's my first time contributing. Please let me know what other things I need to do to get this PR merged.
In Settings page:
While Editing:
Rendered Content:
=> feat: add markdown-it-pivot-table rendering module

server/models/users.js, server/modules/authentication/keycloak/authentication.js, server/modules/authentication/keycloak/definition.yml
This fixes the Keycloak authentication strategy post logout redirect from Keycloak 18 and above when 'Logout from Keycloak on Logout' is enabled. Additionally, a new parameter has been added to the strategy config to enable the old behavior for legacy versions of Keycloak.
This was brought up in discussion #5213 and partially addressed in unmerged #5513. That PR fixes the logout error in Keycloak 18+, but doesn't provide a redirect back to the wiki.
In older versions of Keycloak, the 'redirect_uri' parameter can be passed to the logout endpoint to automatically log out and redirect afterwards. Starting with Keycloak 18, this has been replaced with 'post_logout_redirect_uri'. This parameter must be accompanied by 'id_token_hint' with its value set to the id_token obtained at login.
The …
=> fix: keycloak authentication post logout redirect for Keycloak 18+

package.json, yarn.lock
This PR changes the version of [`markdown-it-pivot-table`](https://www.npmjs.com/package/markdown-it-pivot-table) from 1.0.1 to 1.0.5 which now supports multiple computed columns.
=> chore: upgrade markdown-it-pivot-table version

server/models/sites.mjs
JSON stringifying this causes an error due to expecting type of array.
=> Fix items to be of type array

client/components/tags.vue
The same as https://github.com/requarks/wiki/pull/4280 that resolved https://github.com/requarks/wiki/issues/1180,  but now in the tags component. 
The pagination number was always static based on all pages within the selected tags, now it also reflects the search.
=> fix: page pagination in tags component

dev/templates/legacy.pug
Wiki.js templates uses `polyfill.io` to polyfill `EventSource`. The PR replaces domain `polyfill.io` with `cdnjs.cloudflare.com/polyfill`.
---
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And …
=> refactor(templates): replace `polyfill.io`

dev/helm/templates/deployment.yaml, dev/helm/values.yaml
Before, there was no way to add pod annotations via the helm chart.
=> helm: add pod annotations

server/core/db.js
When something python-like (carvel ytt, ansible etc.) is used in deploying wiki - it is highly likely to have a construction similar to:
```yaml
env:
- name: HA_ACTIVE
value: #@ str(data.values.replicas > 1)
```
which produces `"True"` in config and counter-intuitively does _not_ enable high-availability mode, leading to corresponding issues with caching (page edits not reflected until a lot of refreshes, randomly returning stale pages and so on - because not all workers actually refresh the page cache)
With this simple edit we can significantly decrease user frustration
=> Allow `HA_ACTIVE: True` to enable HA mode

server/controllers/common.js
When attempting to duplicate a page, the operation redirected to an error screen.  
Upon investigation, I found that the issue was caused by a missing `read:source` permission.  
In the Network tab of the Developer Tools, I observed that the server returned a **200 status code** when the error screen was displayed.  
This was misleading, as it indicated a successful response despite the authorization failure.  
This pull request updates the relevant section to ensure that the appropriate status code is returned in cases of unauthorized access.  
---
Steps to reproduce:
1. Attempt to duplicate a page without having `read:source` permission
2. Observe that an error screen is shown
3. Check the Network tab → status code is 200 (incorrect)
=> Bug fix: Incorrect status code on unauthorized access
