locales/de/auth.json, locales/de/common.json, locales/pt/auth.json, locales/pt/common.json, locales/ru/auth.json, locales/ru/common.json
Pull request created by LingoHub based on branch master
=> Additionnal languages (machine translated)

server/locales/zh/auth.json, server/locales/zh/common.json
Pull request created by LingoHub based on branch master
=> LingoHub based on master

README.md
It's called "line breaks" and "GitHub". Source: https://github.github.com/gfm/#soft-line-breaks
=> docs: Fixed terminology

.build/_tasks.js
=> server locales properly applying

server/libs/git.js
Add git branch support to the configs, defaults to master.
config.yml:
```yml
git:
branch: <branch-name>
```
solves issue #215
=> Add git branch support to the configs

CONTRIBUTING.md
Fix URLs for issues, to replace the 404s.
=> Update contributing .md

client/js/components/editor.component.js
=> correct inputting polish letters

server/locales/ja/admin.json, server/locales/ja/browser.json
Fix Japanese Translate
"表示する名前" -> "表示名"
"パスポート" -> "パスワード"
=> Fix Japanese Translate

server/controllers/auth.js, server/middlewares/auth.js
=> feat: redirect to original entry point after auth

dev/examples/docker-compose.yml
Do not merge yet: `wiki_1  | 2019-02-15T10:21:13.005Z [MASTER] error: Failed to connect to Redis instance!`
=> Completely remove Redis dependency Docker-Compose

client/components/admin/admin-groups-edit-permissions.vue, client/components/admin/admin-groups-edit-rules.vue, client/components/admin/admin-groups-edit-users.vue, client/components/editor/editor-wysiwyg.vue, client/modules/localization.js, client/store/admin.js, client/store/index.js, package.json, server/controllers/auth.js, server/db/migrations/2.0.0-beta.148.js, server/db/migrations/2.0.0-beta.205.js, server/db/migrations/2.0.0-beta.99.js, server/db/migrator-source.js, server/graph/resolvers/comment.js, server/graph/resolvers/folder.js, server/graph/resolvers/group.js, server/graph/resolvers/system.js, server/graph/resolvers/tag.js, server/helpers/asset.js, server/helpers/page.js, server/middlewares/upload.js, server/models/analytics.js, server/models/storage.js, server/modules/authentication/discord/authentication.js, server/modules/authentication/github/authentication.js, server/modules/storage/disk/storage.js, server/test/helpers/page.test.js, server/views/error.pug, yarn.lock
Hello! This is my first PR against your project so I hope I did things correctly. I have been liking wiki a lot the past few weeks since I discovered it and wanted to make some contributions. I jumped into the code and figured I would start with something small.
- Going through the code I saw a lot of switch statements so I refactored one into object literals, it benchmarks faster now (although it was a pretty light function to start with). I wouldn't mind refactoring the rest of the switches if that's alright with you!
- I didn't see any tests in there but I saw jest was in some of the nom scripts. I added jest and wrote tests for the function I refactored, I made sure to write them beforehand to make sure all my changes were not changing other things.
Please let me know if this is …
=> Switch converted to Object Literal

client/graph/admin/site/site-mutation-save-config.gql
Add missing SRI security bits. This update fixes error when saving site configuration from admin interface.
=> fix: SRI security toggle

server/models/analytics.js
Support replacing multiple instances of the same template variable in analytics headers
Fixes #1129
=> Use global replace for analytics header templates

server/models/assetFolders.js
Hi,
There's a problem with recursive query on MSSQL.
Mssql don't support WITH RESURSIVE syntax, but equivalent query can be made with union all
Fixes #913
=> Fix assetFolder getHierarchy query for mssql

client/components/admin/admin-pages.vue
admin pages sorted by "last updated" by default. 
#1270
=> admin pages sorted by "last updated" by default

server/modules/search/postgres/engine.js
This fixes search queries with russian locale for me.
=> FIX Postgres Engine to query using right locale

server/modules/rendering/html-core/renderer.js
Ability to open external link in new tab
=> open external link in new tab

client/components/editor/editor-modal-media.vue
=> sort assets by ID and desc

client/components/common/nav-header.vue
Fixing navigation-bar on mobile device, related to issue #1647 and #1651 .
**Screenshot**
=> fix: navbar grid and padding

client/themes/default/components/page.vue
=> change nextTick to onload for anchor scrolling

client/components/admin/admin-pages-visualize.vue
- closes https://github.com/Requarks/wiki/pull/1634 (adds pan/zoom)
- closes https://github.com/Requarks/wiki/issues/1904
- adds ctrl-click to open a page in a new tab
demo: https://imgur.com/a/vMPlHVB
=> /a/pages/visualize improvements

client/components/admin/admin-navigation.vue, client/themes/default/components/nav-sidebar.vue
This fixes icon size when using Font Awesome 5.
fix #1785, fix #1617
**Screenshot**
=> fix: resize Font Awesome icon

server/graph/resolvers/asset.js
fix: #1926
Added permission filtering when listing assets and folders
=> fix: assets permission issues #1926

client/components/comments.vue, client/components/common/nav-header.vue, client/components/editor.vue, client/components/history.vue, client/components/source.vue, client/store/page.js, client/themes/default/components/page.vue, server/controllers/common.js, server/views/editor.pug, server/views/history.pug, server/views/page.pug, server/views/source.pug
fix: #1780
I also fixed the view page icon which doesn't exist
I also fixed the page mode when viewing source page
I have removed all buttons (from both menus) if the user doesn't have the necessary global permissions for them
- I removed non relevant buttons, @NGPixel maybe you prefer just to disable them?
=> feat: Edit / Page Create Buttons showing up even if no action is allowed #1780

server/models/users.js
=> fix: deactivated users can still refresh their token #2101

server/graph/resolvers/page.js
fix: #2071
full outer join doesn't exist on mysql and sqlite.
right join doesn't exist in sqlite.
The solution is implemented based on https://www.sqlitetutorial.net/sqlite-full-outer-join/
=> fix: GraphQL error with MySQL and FULL OUTER JOIN #2071

server/models/pages.js
=> Solving problem with foreing key contraint when page have comments

server/controllers/common.js
same as #2058 (closed) but the target branch is `dev`
=> change language in edit, history and source pages

server/modules/authentication/oidc/authentication.js, server/modules/authentication/oidc/definition.yml
This gets the OIDC authentication method working properly with current wiki and passport-openidconnect.
=> Fix and enable OIDC auth method

server/helpers/error.js
Fixed a copy and paste mistake
=> fix: error name was wrong

server/modules/authentication/discord/definition.yml
Change "discordapp.com" to "discord.com"
=> Discord has a new URL.

client/themes/default/components/tabset.vue
Fix for #2091. The change advised in that issue works brilliantly.
=> fix: tabset tabs can't be scrolled

server/core/db.js, server/graph/resolvers/asset.js, server/master.js, server/models/assetFolders.js, server/models/pages.js, server/modules/rendering/html-image-prefetch/renderer.js, server/modules/rendering/markdown-core/underline.js, server/modules/rendering/markdown-kroki/renderer.js, server/modules/rendering/markdown-plantuml/renderer.js, server/modules/search/elasticsearch/engine.js, server/setup.js, server/test/helpers/page.test.js
+ Remove duplicated await
+ Replace some legacy codes with ES6
+ Fix some of eslint problems
=> [ Refactor server codes ]

client/components/common/search-results.vue
Hello,
as raised in the feedbacks,(https://wiki.js.org/feedback/p/open-new-tab-with-middle-mouse-button-from-search)
I added the possibility to open a search result in a new tab with a middle-click.
Thank you for giving me feedback
=> feat : Add ability to open search result in new tab with middle-click

server/modules/rendering/html-core/renderer.js
suggested fix for the issue mentioned:
https://github.com/Requarks/wiki/discussions/3709#discussioncomment-596783
https://github.com/Requarks/wiki/discussions/3815
=> fix: rendering/html-core - null checks

server/controllers/upload.js
=> Don't allow # in file name

client/themes/default/components/page.vue
=> Add missing decodeURIComponent while page load

server/core/scheduler.js
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
Fixes issues outlined in #4413 and #4405 
I did forget to collect visual evidence (was testing against a production instance) but deployed and observed the fix in action.
I'm making the assumption that this was the intention of the original MR #3821
=> Fixes scheduled git sync task

config.sample.yml, server/core/db.js
I wanted the possibility to use another pg schema than public.
=> Add possibility to set PostgreSQL Schema other than public

server/setup.js
Hi,
Fixes: https://github.com/Requarks/wiki/issues/3980
Best regards,
=> Fix: email toLowerCase

client/components/tags.vue
=> fix Query Parameter on tags page doesn't work

README.md
=> fix(readme): fix nit typo in ngrok link

server/master.js
set bodyParserLimitSize by default to 1mb
permit modifications by environment variable
=> permit bodyParserLimitSize configuration by ENV variable

client/components/welcome.vue
=> feat: Add link to admin area on welcome page

dev/build/Dockerfile
cpu-features build fail
[github action 'Build and push Docker images' stage log error](https://github.com/requarks/wiki/runs/6050848396?check_suite_focus=true#step:7:339)
=> fix: docker build fail

server/core/mail.js
* This header makes emails filtering easier
=> Added X-Mailer header to outgoing emails

server/models/pages.js
=> fix: Show undefined author in git commit when delete page

client/themes/default/components/nav-sidebar.vue
Close https://github.com/requarks/wiki/discussions/5295
Wrong variable name in the sidebar tree
=> fix: Site Tree broken

server/modules/authentication/cas/authentication.js, server/modules/authentication/cas/definition.yml, yarn.lock
Hey there,
i've implemented the CAS workflow. Only tested CAS3.0 so far but it seems to be working just fine :)
=> CAS Authentication

server/modules/comments/default/comment.js
=> Fix: Comment (default) edit not updating content

server/graph/resolvers/page.js
These properties currently not returned and are documented in graphql schema of pages/single method.
=> Added scriptJs and scriptCss

server/graph/resolvers/comment.js, server/models/comments.js
Fix https://github.com/requarks/wiki/discussions/3598
=> fix: Page Rules based on Tag Matches do not work for comment permissions

server/modules/authentication/oidc/authentication.js
Fixed issues with login and "Map Groups".
https://github.com/jaredhanson/passport-openidconnect/blob/101e0f3739157e6f9f0f027f4c8ee4553d6196ff/lib/strategy.js#L210-L237
=> fix: incompatibility issues with passport-openidconnect@0.1.1

server/modules/analytics/umami/code.yml, server/modules/analytics/umami/definition.yml
This module integrates [Umami](https://umami.is) as a analytics provider.
=> feat: add umami as an analytics module

server/modules/authentication/oauth2/authentication.js, server/modules/authentication/oauth2/definition.yml
Allow to map groups.
This a copy paste of the feature of oidc authentication
=> OAuth2: add groups mapping

client/components/admin/admin-pages-visualize.vue
Make it easy to locate the data.
From:
To:
=> sort visualize

server/modules/authentication/oidc/authentication.js, server/modules/authentication/oidc/definition.yml
Added the option for an ACR Value to the OIDC Authentication Module
=> Add ACR Value option to OIDC Module

server/modules/rendering/html-image-prefetch/definition.yml
Just read this and it bothered me.
=> fix: typo in kroki name

dev/helm/Chart.yaml, dev/helm/README.md, dev/helm/templates/deployment.yaml, dev/helm/values.yaml
This pull request introduces the explicit definition of container-level security context and resource requests/limits in the sideload init-container. These changes address security compliance and resource optimization, particularly in environments where security policies impose mandatory requirements on these fields.
=> add support for securityContext and resources in sideload container
